<!--<footer>&copy --><?php //echo date('Y'); ?><!--, INFO LIGHTING CO. All rights reserved</footer>-->
<?php
echo $this->inlineScript()
    ->appendFile($this->basePath('public/js/jquery-1.11.0.min.js', 'text/javascript'))
    ->appendFile($this->basePath('public/js/jquery.backstretch.min.js', 'text/javascript'))
    ->appendFile($this->basePath('public/js/main.min.js'), 'text/javascript');
//    ->prependFile($this->basePath('js/Gettext.js'), 'text/javascript')
//    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
//    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))