<?php
$this->inlineScript()
    ->appendFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'))
//    ->appendFile("http://code.jquery.com/jquery-migrate-1.2.1.js", 'text/javascript')
    ->appendFile($this->basePath('vendor/bettertable/js/jquery.form.min.js', 'text/javascript'))
    // ckeditor related
    ->appendFile($this->basePath('vendor/ckeditor/ckeditor/ckeditor.js', 'text/javascript'))
    ->appendFile($this->basePath('vendor/ckeditor/ckeditor/adapters/jquery.js', 'text/javascript'))
    // jquery plugins
    ->appendFile($this->basePath('vendor/bettertable/js/jquery.datetimepicker.js', 'text/javascript'))
    ->appendFile($this->basePath('vendor/bettertable/js/jquery.selectBox.min.js', 'text/javascript'));

if (APPLICATION_ENV == "development") {
    // bettertable related
    $this->inlineScript()->appendFile($this->basePath('vendor/bettertable/js/lib.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/FileUploader.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/TableEntity.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/FileManager.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/TablePaginator.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/TableJoin.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/TableCellEditor.js', 'text/javascript'))
        ->appendFile($this->basePath('vendor/bettertable/js/jquery.bettertable.js', 'text/javascript'));
} else {
    $this->inlineScript()->appendFile($this->basePath('vendor/bettertable/js/jquery.bettertable.1.0.min.js', 'text/javascript'));
}
// rest
$this->inlineScript()->appendFile($this->basePath('js/Gettext.js'), 'text/javascript')
    ->appendFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->appendFile($this->basePath('js/lib' . (APPLICATION_ENV == "development" ? "" : ".min") . '.js'), 'text/javascript')
    ->appendFile($this->basePath('js/admin/admin-main' . (APPLICATION_ENV == "development" ? "" : ".min") . '.js'), 'text/javascript');

echo $this->inlineScript();
