<?php
$this->inlineScript()
    ->appendFile($this->basePath('public/js/jquery-1.11.0.min.js', 'text/javascript'))
    // jquery plugins
    ->appendFile($this->basePath('vendor/bettertable/js/plugins.min.js', 'text/javascript'))
    // ckeditor related
    ->appendFile($this->basePath('vendor/ckeditor/ckeditor/ckeditor.js', 'text/javascript'))
    ->appendFile($this->basePath('vendor/ckeditor/ckeditor/adapters/jquery.js', 'text/javascript'))
    // bettertabel
    ->appendFile($this->basePath('vendor/bettertable/js/bettertable.min.js', 'text/javascript'))
    // main js
    ->appendFile($this->basePath('public/js/admin/admin.min.js'), 'text/javascript');

echo $this->inlineScript();
