<head>
    <?php
    $child = $this->child;
    $isMobile = $this->mobile();
    $pageTitle = (isset($child->pageTitle)) ? $websiteName . " - " . $child->pageTitle : $websiteName . " - " . ucwords($this->routeName()) ;
    $follow = (isset($child->follow)) ? "noindex, nofollow" : "feed, follow, archieve";

    // The website's title.
    echo $this->headTitle($pageTitle);

    // The meta tags
    $description = isset($child->metaInfo['description']) ? $child->metaInfo['description'] : 'Interlight is a company that specializes in lighting technology and equipment';
    $keywords = isset($child->metaInfo['keywords']) ? $child->metaInfo['keywords'] : 'info, lighting, products, equipment, led, lamp';

    // We append everything to the headMeta
    $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', $description)
        ->appendName('keywords', $keywords)
        ->appendName('robots', $follow)
        ->appendName('language', 'el')
        ->appendName('googlebot', $follow);
    echo $this->headMeta();

    // We add the favicon and our stylesheets
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('public/images/favicon.ico')))
//         ->headLink(array('rel' => 'gettext', 'type' => 'application/x-po', 'href' => $this->basePath('module/Application/language/'.$this->plugin('translate')->getTranslator()->getLocale().'.po')))
//        ->prependStylesheet($this->basePath('css/print'. (APPLICATION_ENV == "development" ? "":".min") . '.css'),'print')
        ->prependStylesheet($this->basePath('public/css/style.css'));

    $this->headScript()->appendFile($this->basePath('public/js/modernizr.min.js'));

    echo $this->headScript();

    echo $this->headLink();

    // Some scripts the must be outputted first follow below
    ?>
    <script>var baseUrl = '<?php echo $this->basePath(); ?>',isMobile = <?php echo $isMobile ? 'true':'false'; ?>;</script>
</head>