<div id="infoWrapper"<?php echo !$this->useFull ? 'class="shortened"' : ''; ?>>
    <img src="<?php echo $this->basePath('public/images/' . $this->sideBg . '-side-bg.png'); ?>" class="sideBackground"
         alt="main background"/>

    <section id="contact">
        <h2>Πληροφοριες</h2>
        <ul>
            <li>
                <a href="https://goo.gl/maps/QIQEM" title="View in Google Maps" target="_blank">
                    <img src="<?php echo $this->basePath('public/images/location-icon.png'); ?>" width="40" height="30"
                         alt="location icon"/>
                    <h3><?php echo $this->getContent('location'); ?></h3>
                </a>
            </li>
            <li>
                <img src="<?php echo $this->basePath('public/images/appointment-icon.png'); ?>" width="40" height="30"
                     alt="appointment icon"/>
                <h3><?php echo $this->getContent('appointment'); ?></h3>
            </li>
            <li>
                <img src="<?php echo $this->basePath('public/images/telephone-icon.png'); ?>" width="40" height="30"
                     alt="telephone icon"/>
                <h3><?php echo $this->getContent('telephone'); ?></h3>
            </li>
            <li>
                <img src="<?php echo $this->basePath('public/images/mobile-icon.png'); ?>" width="40" height="30"
                     alt="mobile icon"/>
                <h3><?php echo $this->getContent('mobile'); ?></h3>
            </li>
            <li>
                <?php $email = $this->getContent('email'); ?>
                <a href="mailto:<?php echo $email; ?>" target="_blank">
                    <img src="<?php echo $this->basePath('public/images/email-icon.png'); ?>" width="40" height="30"
                         alt="email icon"/>
                    <h3><?php echo $email ?></h3>
                </a>
            </li>
        </ul>
    </section>
    <?php if($this->showQuote): ?>
    <span class="quote notranslate"><?php echo $this->getContent('front_page_quote'); ?></span>
    <?php endif; ?>
</div>