<?php
/**
 * @var \Zend\Paginator\Paginator $paginator
 */

$pages = $paginator->getPages()->pageCount;
$current = $paginator->getCurrentPageNumber();
?>
<ul class="tablePagination" data-items="<?php echo $paginator->getTotalItemCount(); ?>">
    <!-- Previous page link -->
    <?php if ($current - 1 > 0): ?>
        <li>
            <a href="#?page=<?php echo $this->previous; ?>"><<</a>
        </li>
    <?php else: ?>
        <li>
            <span class="disabled">Previous</span>
        </li>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php if ($pages > 0):
    for ($i = 1; $i <= $pages; $i++):
        ?>
        <?php if ($i != $current): ?>
        <li>
            <a href="#?page=<?php echo $i; ?>">
                <?php echo $i; ?>
            </a>
        </li>
    <?php else: ?>
        <li class="active">
            <a href="#?"><?php echo $i; ?></a>
        </li>
    <?php endif; ?>
    <?php endfor;
    else:
    ?>
    <li class="active">
        <a href="#?">0</a>
    </li>
    <?php endif; ?>

    <!--Next page link-->
    <?php if ($current + 1 < $pages): ?>
        <li>
            <a href="#?page=<?php echo $this->next; ?>">
                >>
            </a>
        </li>
    <?php else: ?>
        <li>
            <span class="disabled">Next</span>
        </li>
    <?php endif; ?>
</ul>