<?php

namespace DoctrineORMModule\Proxy\__CG__\Image\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gallery extends \Image\Entity\Gallery implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'subGalleries', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'galleryId', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'images', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'name', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'parentGallery', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'url');
        }

        return array('__isInitialized__', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'subGalleries', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'galleryId', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'images', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'name', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'parentGallery', '' . "\0" . 'Image\\Entity\\Gallery' . "\0" . 'url');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gallery $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function encodeUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encodeUrl', array());

        return parent::encodeUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubGalleries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubGalleries', array());

        return parent::getSubGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubGalleries($subGalleries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubGalleries', array($subGalleries));

        return parent::setSubGalleries($subGalleries);
    }

    /**
     * {@inheritDoc}
     */
    public function getGalleryId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getGalleryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGalleryId', array());

        return parent::getGalleryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGalleryId($galleryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGalleryId', array($galleryId));

        return parent::setGalleryId($galleryId);
    }

    /**
     * {@inheritDoc}
     */
    public function addImages(\Image\Entity\GalleryImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImages', array($image));

        return parent::addImages($image);
    }

    /**
     * {@inheritDoc}
     */
    public function clearImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearImages', array());

        return parent::clearImages();
    }

    /**
     * {@inheritDoc}
     */
    public function removeImages(\Image\Entity\GalleryImage $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImages', array($image));

        return parent::removeImages($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', array($images));

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentGallery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentGallery', array());

        return parent::getParentGallery();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentGallery($parentGallery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentGallery', array($parentGallery));

        return parent::setParentGallery($parentGallery);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

}
