<main role="main">
    <?php echo $this->partial('info', array('sideBg' => 'services')); ?>
    <div class="contentWrapper">
        <h2>Υπηρεσιες</h2>
        <ul id="services">
            <?php foreach ($this->services as $service):
                ?>
                <li>
                    <div class="serviceInfo">
                        <img
                            src="<?php echo $this->basePath('public/images/services/' . $service->getThumbnail("list")); ?>"/>
                        <a href="<?php echo $this->url("services_index/view", array("serviceUrl" => $service->getUrl())); ?>"
                           class="readMore">Πατήστε εδώ για πληροφορίες.</a>
                    </div>
                    <div class="serviceBody">
                        <h3><?php echo $service->getName(); ?></h3>

                        <div class="serviceSnippet"><?php echo $service->getSnippet(); ?></div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</main>
