<div class="tableWrapper" data-entity="services">
    <?php echo $this->partial("table_options", array(
        "paginator" => $this->paginator,
        "location" => "services"
    )); ?>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span class="sortable"><?php echo $this->translate("Name"); ?></span>
            <span><?php echo $this->translate("Snippet"); ?></span>
            <span><?php echo $this->translate("Content"); ?></span>
            <span><?php echo $this->translate("Thumbnail"); ?></span>
        </div>
    </div>
    <div class="tableBody">
        <?php
        foreach ($this->paginator as $service)
            echo $this->partial('service', array(
                "service" => $service
            ));
        ?>
    </div>
</div>