<?php echo $this->partial('info',array('sideBg' => 'services')); ?>
<div id="post">
    <img class="postThumbnail" src="<?php echo $this->basePath('images/services/' . $service->getThumbnail()); ?>"
         alt="post thumbnail"/>

    <div class="postHeader">
        <h1><?php echo $service->getName(); ?></h1>
    </div>

    <div class="postBody">
        <?php echo $service->getContent(); ?>
    </div>
</div>