<main role="main">
    <?php echo $this->partial('info', array('sideBg' => 'services')); ?>
    <div class="contentWrapper">
        <article id="post">
            <h2><?php echo $service->getName(); ?></h2>
            <img src="<?php echo $this->basePath('public/images/services/' . $service->getThumbnail()); ?>"
                 alt="post thumbnail"/>

            <div class="postBody">
                <?php echo $service->getContent(); ?>
            </div>
        </article>
    </div>
</main>