<?php if ($this->activeGallery instanceof \Image\Entity\Gallery):
$images = $this->activeGallery->getImages()->toArray();
usort($images, function ($a, $b) {
    return $a->getPosition() > $b->getPosition();
});
?>
<main role="main">
    <?php echo $this->partial('info', array('sideBg' => 'galleries')); ?>
    <div class="contentWrapper">
        <aside id="galleries">
            <h2>Φωτογραφιες</h2>
            <nav>
                <ul>
                    <?php
                    foreach ($this->galleries as $gallery):
                        $name = $gallery->getName();
                        ?>
                        <li<?php echo $this->activeGallery->getName() == $name ? ' class="active"' : ""; ?>>
                            <a href="<?php echo $this->url("galleries_index", array("galleryName" => $gallery->getUrl())); ?>"
                               title="Δείτε την γκαλλερί <?php echo $name; ?>"><?php echo $name; ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </aside>
        <section id="imagePreview">
            <div id="imagePreviewWrapper">
                <?php $firstImage = $images[0]; ?>
                <img
                    src="<?php echo $this->basePath('public/images/gallery/' . $firstImage->getImage()->getImage()); ?>">
            </div>
            <span><?php echo $firstImage->getTitle(); ?></span>
        </section>
        <section id="images">
            <ul>
                <?php
                /**
                 * @var \Image\Entity\GalleryImage $galleryImage
                 */
                foreach ($images as $index => $galleryImage):?>
                    <li<?php echo $index == 0 ? ' class="active"' : ''; ?>>
                        <img
                            src="<?php echo $this->basePath('public/images/gallery/' . $galleryImage->getImage()->getImage('list')); ?>">
                        <span><?php echo $galleryImage->getTitle(); ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </section>
    </div>
</main>
