<div class="formWrapper">
    <h2>Website Settings</h2>
    <?php
    echo $this->showMessages();

    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('setting');
    $form->setAttribute('action', $this->url('settings'));
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        $image = $fieldset->get('aboutProfileImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <div class="element">
        <?php
        $image = $fieldset->get('homeImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <div class="element">
        <?php
        $image = $fieldset->get('aboutImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <div class="element">
        <?php
        $image = $fieldset->get('galleriesImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <div class="element">
        <?php
        $image = $fieldset->get('servicesImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <div class="element">
        <?php
        $image = $fieldset->get('contactImage');
        echo $this->formLabel($image);
        echo $this->formElementErrors($image, array('class' => 'formError'));
        echo $this->formFile($image);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Update'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>