<div class="formWrapper">
    <h2>Add a new Post</h2>
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('post');
    $form->setAttribute('action', $this->url('posts/add'));
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        $title = $fieldset->get('title');
        echo $this->formLabel($title);
        echo $this->formElementErrors($title, array('class' => 'formError'));
        echo $this->formInput($title);
        ?>
    </div>
    <div class="element">
        <?php
        $content = $fieldset->get('content');
        echo $this->formLabel($content);
        echo $this->formElementErrors($content, array('class' => 'formError'));
        echo $this->formTextarea($content);
        ?>
    </div>
    <div class="element">
        <?php
        $thumbnail = $fieldset->get('thumbnail');
        echo $this->formLabel($thumbnail);
        echo $this->formElementErrors($thumbnail, array('class' => 'formError'));
        echo $this->formFile($thumbnail);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>