<?php
$time = $post->getPostDate();
?>
<main role="main">
    <?php echo $this->partial('info', array('sideBg' => 'home')); ?>
    <div class="contentWrapper">
        <article id="post">
            <h2><?php echo $post->getTitle(); ?></h2>
            <img src="<?php echo $this->basePath('public/images/posts/' . $post->getThumbnail()); ?>"
                 alt="post thumbnail"/>

            <section class="postBody">
                <time datetime="<?php echo $time->format('c');?>"><?php echo $time->format('n F, Y'); ?></time>
                <?php echo $post->getContent(); ?>
            </section>
        </article>
    </div>
</main>