<div class="tableWrapper" data-entity="contents" data-deletable="false" data-creatable="false">
    <h2>Website Text Contents</h2>
    <div class="tableHeader">
        <div class="tableColumn">
            <span>Id</span>
            <span><?php echo $this->translate("Name"); ?></span>
            <span><?php echo $this->translate("Content"); ?></span>
        </div>
    </div>
    <div class="tableBody">
        <?php
        /**
         * @var \Application\Entity\Content $content
         */
        foreach ($this->contents as $content):
            $contentText = $content->getContent();
            ?>
            <div class="tableColumn">
                <div data-attribute="entityId"><span class="tableCellText"><?php echo $content->getTarget(); ?></span></div>
                <div data-attribute="name" data-editable="false">
                    <span class="tableCellText"><?php echo $content->getName(); ?></span>
                </div>
                <div data-attribute="content" data-type="<?php echo $content->getIsTextarea() ? "textarea" : "text"; ?>">
                        <span class="tableCellText"><?php echo $contentText ? htmlentities($contentText) : "-"; ?></span>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
