<div class="formWrapper">
    <h2>Add a new User</h2>
    <?php
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('user');
    $form->prepare();
    $form->setAttribute('action', $this->url('users/add'));
    echo $this->form()->openTag($form);
    //echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        $username = $fieldset->get('username');
        echo $this->formLabel($username);
        echo $this->formElementErrors($username, array('class' => 'formError'));
        echo $this->formInput($username);
        ?>
    </div>
    <div class="element">
        <?php
        $password = $fieldset->get('password');
        echo $this->formLabel($password);
        echo $this->formElementErrors($password, array('class' => 'formError'));
        echo $this->formPassword($password);
        ?>
    </div>
    <div class="element">
        <?php
        $email = $fieldset->get('email');
        echo $this->formLabel($email);
        echo $this->formElementErrors($email, array('class' => 'formError'));
        echo $this->formEmail($email);
        ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
    <?php echo $this->form()->closeTag() ?>
</div>