<?php
/**
 * @var \Post\Entity\Post $post
 */
$thumbnail = $post->getThumbnail("admin");
?>
<div class="tableColumn">
    <div data-attribute="entityId">
        <span class="tableCellText"><?php echo $post->getPostId(); ?></span>
    </div>
    <div data-attribute="title">
        <span class="tableCellText"><?php echo $post->getTitle(); ?></span>
    </div>
    <div data-attribute="content" data-type="textarea">
        <span class="tableCellText"><?php echo htmlentities($post->getContent()); ?></span>
    </div>
    <div data-attribute="thumbnail" data-type="image">
        <span class="tableCellMeta">{"location":"images/posts","current" : "<?php echo $thumbnail ? $thumbnail : ''; ?>", "prefix": "post"}</span>
                    <span class="tableCellText">
                        <?php echo $thumbnail ? '<img src="' . $this->basePath('public/images/posts/' . $thumbnail) . '" width="100" height="70" alt="' . $this->translate("post image") . '" />' : '-'; ?>
                    </span>
    </div>
</div>