<?php
/**
 * @var \Post\Entity\Service $service
 */
$thumbnail = $service->getThumbnail("admin");
?>
<div class="tableColumn">
    <div data-attribute="entityId">
        <span class="tableCellText"><?php echo $service->getServiceId(); ?></span>
    </div>
    <div data-attribute="name">
        <span class="tableCellText"><?php echo $service->getName(); ?></span>
    </div>
    <div data-attribute="snippet" data-type="textarea">
        <span class="tableCellText"><?php echo htmlentities($service->getSnippet()); ?></span>
    </div>
    <div data-attribute="content" data-type="textarea">
        <span class="tableCellText"><?php echo htmlentities($service->getContent()); ?></span>
    </div>
    <div data-attribute="thumbnail" data-type="image">
        <span class="tableCellMeta">{"location":"images/services","current" : "<?php echo $thumbnail ? $thumbnail : ''; ?>", "prefix": "service"}</span>
                    <span class="tableCellText">
                        <?php echo $thumbnail ? '<img src="' . $this->basePath('images/services/' . $thumbnail) . '" width="100" height="70" alt="' . $this->translate("service image") . '" />' : '-'; ?>
                    </span>
    </div>
</div>