<main id="aboutPage">
    <?php echo $this->partial('info', array('sideBg' => 'about')); ?>
    <div class="contentWrapper">
        <h2>Σχετικα με μας</h2>

        <div id="aboutInfo">
            <img class="thumbnail" src="<?php echo $this->basePath('public/images/about-profile.png'); ?>" width="350"
                 height="232"/>
            <span><?php echo $this->getContent('signature'); ?></span>
        </div>

        <div id="aboutBody">
            <?php echo $this->getContent("about_me"); ?>
        </div>
    </div>
</main>