<?php echo $this->partial('info',array('sideBg' => 'home', 'useFull' => true, 'showQuote' => true)); ?>
<ul id="posts">
    <?php foreach ($this->posts as $post): ?>
        <li>
            <a href="<?php echo $this->url('post_view', array("postUrl" => $post->getUrl())); ?>">
                <img
                    src="<?php echo $this->basePath('images/posts/' . $post->getThumbnail("list")); ?>"
                    class="postThumbnail" width="350" height="250"/>
                <span class="postTitle"><?php echo $post->getTitle(); ?></span>
            </a>
        </li>
    <?php endforeach; ?>
</ul>